// Autogenerated lightweight commercial summary for Operations Dashboard and Analytics
export interface RevenueSummaryData {
  fxRateUSDToAED: number;
  totalRevenueUSD: number;
  totalOperRevenueUSD: number;
  totalStandbyRevenueUSD: number;
  totalRevenueAED: number;
  totalOperRevenueAED: number;
  totalStandbyRevenueAED: number;
  totalRevenue: number;
  totalOperRevenue: number;
  totalStandbyRevenue: number;
  totalOperDays: number;
  totalStandbyDays: number;
  totalTools: number;
  totalCategories: number;
  totalSizes: number;
  totalContracts: number;
}

export interface CategoryRevenueSummary {
  category: string;
  totalRevenueUSD: number;
  operRevenueUSD: number;
  standbyRevenueUSD: number;
  totalRevenueAED: number;
  operRevenueAED: number;
  standbyRevenueAED: number;
  totalRevenue: number;
  operRevenue: number;
  standbyRevenue: number;
  operDays: number;
  standbyDays: number;
  toolCount?: number;
  toolsCount?: number;
  jobsCount: number;
}

export interface ContractRevenueSummary {
  contractKey?: string;
  contract: string;
  client: string;
  currency: 'AED' | 'USD';
  nativeRevenue: number;
  nativeOperRevenue: number;
  nativeStandbyRevenue: number;
  totalRevenueUSD: number;
  operRevenueUSD: number;
  standbyRevenueUSD: number;
  totalRevenueAED: number;
  operRevenueAED: number;
  standbyRevenueAED: number;
  totalRevenue: number;
  operRevenue: number;
  standbyRevenue: number;
  operDays?: number;
  standbyDays?: number;
  toolCount?: number;
  toolsCount?: number;
  jobsCount: number;
}

export const REVENUE_SUMMARY: RevenueSummaryData = {
  "fxRateUSDToAED": 3.6725,
  "totalRevenueUSD": 30164707.69,
  "totalOperRevenueUSD": 17793820.16,
  "totalStandbyRevenueUSD": 11551079.41,
  "totalRevenueAED": 110779898.52,
  "totalOperRevenueAED": 65347800.68,
  "totalStandbyRevenueAED": 42421356.95,
  "totalRevenue": 30164707.69,
  "totalOperRevenue": 17793820.16,
  "totalStandbyRevenue": 11551079.41,
  "totalOperDays": 137372.0,
  "totalStandbyDays": 760216.0,
  "totalTools": 6882,
  "totalCategories": 97,
  "totalSizes": 213,
  "totalContracts": 28
};

export const TOP_CATEGORIES_REVENUE: CategoryRevenueSummary[] = [
  {
    "category": "OTHER DOWNHOLE TOOL",
    "totalRevenueUSD": 5270566.82,
    "operRevenueUSD": 4243152.65,
    "standbyRevenueUSD": 555917.71,
    "totalRevenueAED": 19356157.16,
    "operRevenueAED": 15582977.77,
    "standbyRevenueAED": 2041608.96,
    "totalRevenue": 5270566.82,
    "operRevenue": 4243152.65,
    "standbyRevenue": 555917.71,
    "operDays": 11181.0,
    "standbyDays": 28196.0,
    "toolsCount": 467,
    "jobsCount": 686
  },
  {
    "category": "DRILLING JAR",
    "totalRevenueUSD": 4087329.13,
    "operRevenueUSD": 1799081.72,
    "standbyRevenueUSD": 2266337.6,
    "totalRevenueAED": 15010724.04,
    "operRevenueAED": 6607127.51,
    "standbyRevenueAED": 8323134.26,
    "totalRevenue": 4087329.13,
    "operRevenue": 1799081.72,
    "standbyRevenue": 2266337.6,
    "operDays": 7093.0,
    "standbyDays": 16140.0,
    "toolsCount": 218,
    "jobsCount": 300
  },
  {
    "category": "WHIPSTOCK",
    "totalRevenueUSD": 2810457.65,
    "operRevenueUSD": 2726631.8,
    "standbyRevenueUSD": 83825.85,
    "totalRevenueAED": 10321405.9,
    "operRevenueAED": 10013555.47,
    "standbyRevenueAED": 307850.43,
    "totalRevenue": 2810457.65,
    "operRevenue": 2726631.8,
    "standbyRevenue": 83825.85,
    "operDays": 60.0,
    "standbyDays": 794.0,
    "toolsCount": 69,
    "jobsCount": 64
  },
  {
    "category": "BIT SUB",
    "totalRevenueUSD": 1853288.25,
    "operRevenueUSD": 745947.89,
    "standbyRevenueUSD": 1107340.36,
    "totalRevenueAED": 6806200.6,
    "operRevenueAED": 2739493.6,
    "standbyRevenueAED": 4066706.57,
    "totalRevenue": 1853288.25,
    "operRevenue": 745947.89,
    "standbyRevenue": 1107340.36,
    "operDays": 7044.0,
    "standbyDays": 45904.0,
    "toolsCount": 376,
    "jobsCount": 613
  },
  {
    "category": "ROLLER REAMER",
    "totalRevenueUSD": 1707480.05,
    "operRevenueUSD": 1137527.54,
    "standbyRevenueUSD": 563759.01,
    "totalRevenueAED": 6270720.24,
    "operRevenueAED": 4177569.59,
    "standbyRevenueAED": 2070404.84,
    "totalRevenue": 1707480.05,
    "operRevenue": 1137527.54,
    "standbyRevenue": 563759.01,
    "operDays": 1733.0,
    "standbyDays": 2109.0,
    "toolsCount": 232,
    "jobsCount": 245
  },
  {
    "category": "STRING STAB",
    "totalRevenueUSD": 1432207.81,
    "operRevenueUSD": 728273.08,
    "standbyRevenueUSD": 684964.37,
    "totalRevenueAED": 5259785.82,
    "operRevenueAED": 2674581.28,
    "standbyRevenueAED": 2515537.06,
    "totalRevenue": 1432207.81,
    "operRevenue": 728273.08,
    "standbyRevenue": 684964.37,
    "operDays": 7705.0,
    "standbyDays": 18589.0,
    "toolsCount": 348,
    "jobsCount": 288
  },
  {
    "category": "DIVERTER",
    "totalRevenueUSD": 1295116.03,
    "operRevenueUSD": 1032571.7,
    "standbyRevenueUSD": 239803.13,
    "totalRevenueAED": 4756313.59,
    "operRevenueAED": 3792119.54,
    "standbyRevenueAED": 880677.01,
    "totalRevenue": 1295116.03,
    "operRevenue": 1032571.7,
    "standbyRevenue": 239803.13,
    "operDays": 1068.0,
    "standbyDays": 681.0,
    "toolsCount": 26,
    "jobsCount": 91
  },
  {
    "category": "AUTO DRILLER",
    "totalRevenueUSD": 946735.57,
    "operRevenueUSD": 474390.67,
    "standbyRevenueUSD": 472344.9,
    "totalRevenueAED": 3476886.36,
    "operRevenueAED": 1742199.78,
    "standbyRevenueAED": 1734686.67,
    "totalRevenue": 946735.57,
    "operRevenue": 474390.67,
    "standbyRevenue": 472344.9,
    "operDays": 546.0,
    "standbyDays": 1086.0,
    "toolsCount": 8,
    "jobsCount": 64
  },
  {
    "category": "ANNULAR BOP",
    "totalRevenueUSD": 940328.44,
    "operRevenueUSD": 751040.57,
    "standbyRevenueUSD": 189287.87,
    "totalRevenueAED": 3453356.19,
    "operRevenueAED": 2758196.45,
    "standbyRevenueAED": 695159.66,
    "totalRevenue": 940328.44,
    "operRevenue": 751040.57,
    "standbyRevenue": 189287.87,
    "operDays": 697.0,
    "standbyDays": 340.0,
    "toolsCount": 9,
    "jobsCount": 57
  },
  {
    "category": "13-5/8\" DOUBLE BOP",
    "totalRevenueUSD": 607126.08,
    "operRevenueUSD": 448544.84,
    "standbyRevenueUSD": 158581.24,
    "totalRevenueAED": 2229670.53,
    "operRevenueAED": 1647280.89,
    "standbyRevenueAED": 582389.61,
    "totalRevenue": 607126.08,
    "operRevenue": 448544.84,
    "standbyRevenue": 158581.24,
    "operDays": 487.0,
    "standbyDays": 450.0,
    "toolsCount": 20,
    "jobsCount": 37
  }
];

export const TOP_CONTRACTS_REVENUE: ContractRevenueSummary[] = [
  {
    "contractKey": "4700023861 - ADNOC ONSHORE - RENTALS",
    "contract": "4700023861",
    "client": "ADNOC ONSHORE - RENTALS",
    "currency": "USD",
    "nativeRevenue": 7818502.12,
    "nativeOperRevenue": 5780933.84,
    "nativeStandbyRevenue": 1217761.43,
    "totalRevenueUSD": 7818502.12,
    "operRevenueUSD": 5780933.84,
    "standbyRevenueUSD": 1217761.43,
    "totalRevenueAED": 28713448.68,
    "operRevenueAED": 21230479.26,
    "standbyRevenueAED": 4472229.09,
    "totalRevenue": 7818502.12,
    "operRevenue": 5780933.84,
    "standbyRevenue": 1217761.43,
    "operDays": 52276.0,
    "standbyDays": 29947.0,
    "toolsCount": 1063,
    "jobsCount": 451
  },
  {
    "contractKey": "4700024096 - ADNOC DRILLING - RENTALS",
    "contract": "4700024096",
    "client": "ADNOC DRILLING - RENTALS",
    "currency": "AED",
    "nativeRevenue": 19708565.83,
    "nativeOperRevenue": 6849528.43,
    "nativeStandbyRevenue": 12859037.39,
    "totalRevenueUSD": 5366522.83,
    "operRevenueUSD": 1865086.96,
    "standbyRevenueUSD": 3501434.6,
    "totalRevenueAED": 19708565.83,
    "operRevenueAED": 6849528.43,
    "standbyRevenueAED": 12859037.39,
    "totalRevenue": 5366522.83,
    "operRevenue": 1865086.96,
    "standbyRevenue": 3501434.6,
    "operDays": 25617.0,
    "standbyDays": 60341.0,
    "toolsCount": 760,
    "jobsCount": 24
  },
  {
    "contractKey": "444558 - ADNOC OFFSHORE",
    "contract": "444558",
    "client": "ADNOC OFFSHORE",
    "currency": "USD",
    "nativeRevenue": 5084728.21,
    "nativeOperRevenue": 2262800.14,
    "nativeStandbyRevenue": 2821928.07,
    "totalRevenueUSD": 5084728.21,
    "operRevenueUSD": 2262800.14,
    "standbyRevenueUSD": 2821928.07,
    "totalRevenueAED": 18673663.8,
    "operRevenueAED": 8310133.49,
    "standbyRevenueAED": 10363530.22,
    "totalRevenue": 5084728.21,
    "operRevenue": 2262800.14,
    "standbyRevenue": 2821928.07,
    "operDays": 7678.0,
    "standbyDays": 274205.0,
    "toolsCount": 3850,
    "jobsCount": 381
  },
  {
    "contractKey": "4700023861 - ADNOC",
    "contract": "4700023861",
    "client": "ADNOC",
    "currency": "USD",
    "nativeRevenue": 2368793.72,
    "nativeOperRevenue": 1042125.4,
    "nativeStandbyRevenue": 1326668.32,
    "totalRevenueUSD": 2368793.72,
    "operRevenueUSD": 1042125.4,
    "standbyRevenueUSD": 1326668.32,
    "totalRevenueAED": 8699394.68,
    "operRevenueAED": 3827205.65,
    "standbyRevenueAED": 4872189.2,
    "totalRevenue": 2368793.72,
    "operRevenue": 1042125.4,
    "standbyRevenue": 1326668.32,
    "operDays": 3227.0,
    "standbyDays": 118837.0,
    "toolsCount": 2027,
    "jobsCount": 59
  },
  {
    "contractKey": "444558.REV.1 - ADNOC OFFSHORE",
    "contract": "444558.REV.1",
    "client": "ADNOC OFFSHORE",
    "currency": "USD",
    "nativeRevenue": 1746152.91,
    "nativeOperRevenue": 854386.25,
    "nativeStandbyRevenue": 891766.66,
    "totalRevenueUSD": 1746152.91,
    "operRevenueUSD": 854386.25,
    "standbyRevenueUSD": 891766.66,
    "totalRevenueAED": 6412746.35,
    "operRevenueAED": 3137733.48,
    "standbyRevenueAED": 3275012.78,
    "totalRevenue": 1746152.91,
    "operRevenue": 854386.25,
    "standbyRevenue": 891766.66,
    "operDays": 34879.0,
    "standbyDays": 115435.0,
    "toolsCount": 1826,
    "jobsCount": 130
  },
  {
    "contractKey": "4700012465 - ADNOC ONSHORE - RENTALS",
    "contract": "4700012465",
    "client": "ADNOC ONSHORE - RENTALS",
    "currency": "USD",
    "nativeRevenue": 1421150.0,
    "nativeOperRevenue": 1421150.0,
    "nativeStandbyRevenue": 0.0,
    "totalRevenueUSD": 1421150.0,
    "operRevenueUSD": 1421150.0,
    "standbyRevenueUSD": 0.0,
    "totalRevenueAED": 5219173.58,
    "operRevenueAED": 5219173.58,
    "standbyRevenueAED": 0.0,
    "totalRevenue": 1421150.0,
    "operRevenue": 1421150.0,
    "standbyRevenue": 0.0,
    "operDays": 1235.0,
    "standbyDays": 4730.0,
    "toolsCount": 257,
    "jobsCount": 60
  },
  {
    "contractKey": "4700024608 - UDR - ADNOC DRILLING - FISHING",
    "contract": "4700024608 - UDR",
    "client": "ADNOC DRILLING - FISHING",
    "currency": "USD",
    "nativeRevenue": 1331259.46,
    "nativeOperRevenue": 525945.14,
    "nativeStandbyRevenue": 805314.32,
    "totalRevenueUSD": 1331259.46,
    "operRevenueUSD": 525945.14,
    "standbyRevenueUSD": 805314.32,
    "totalRevenueAED": 4889050.33,
    "operRevenueAED": 1931533.52,
    "standbyRevenueAED": 2957516.84,
    "totalRevenue": 1331259.46,
    "operRevenue": 525945.14,
    "standbyRevenue": 805314.32,
    "operDays": 1283.0,
    "standbyDays": 77722.0,
    "toolsCount": 811,
    "jobsCount": 129
  },
  {
    "contractKey": "4700018368 - ADNOC DRILLING - WHIPSTOCK",
    "contract": "4700018368",
    "client": "ADNOC DRILLING - WHIPSTOCK",
    "currency": "USD",
    "nativeRevenue": 1092781.8,
    "nativeOperRevenue": 1092781.8,
    "nativeStandbyRevenue": 0.0,
    "totalRevenueUSD": 1092781.8,
    "operRevenueUSD": 1092781.8,
    "standbyRevenueUSD": 0.0,
    "totalRevenueAED": 4013241.15,
    "operRevenueAED": 4013241.15,
    "standbyRevenueAED": 0.0,
    "totalRevenue": 1092781.8,
    "operRevenue": 1092781.8,
    "standbyRevenue": 0.0,
    "operDays": 225.0,
    "standbyDays": 2276.0,
    "toolsCount": 139,
    "jobsCount": 8
  },
  {
    "contractKey": "16358.13.Rev2 - ADNOC ONSHORE - FISHING",
    "contract": "16358.13.Rev2",
    "client": "ADNOC ONSHORE - FISHING",
    "currency": "USD",
    "nativeRevenue": 1063866.32,
    "nativeOperRevenue": 805777.44,
    "nativeStandbyRevenue": 258088.88,
    "totalRevenueUSD": 1063866.32,
    "operRevenueUSD": 805777.44,
    "standbyRevenueUSD": 258088.88,
    "totalRevenueAED": 3907049.14,
    "operRevenueAED": 2959217.46,
    "standbyRevenueAED": 947831.28,
    "totalRevenue": 1063866.32,
    "operRevenue": 805777.44,
    "standbyRevenue": 258088.88,
    "operDays": 3985.0,
    "standbyDays": 14421.0,
    "toolsCount": 1493,
    "jobsCount": 56
  },
  {
    "contractKey": "16358.13.Rev1 - ADNOC ONSHORE - FISHING",
    "contract": "16358.13.Rev1",
    "client": "ADNOC ONSHORE - FISHING",
    "currency": "USD",
    "nativeRevenue": 946594.12,
    "nativeOperRevenue": 674926.48,
    "nativeStandbyRevenue": 271667.64,
    "totalRevenueUSD": 946594.12,
    "operRevenueUSD": 674926.48,
    "standbyRevenueUSD": 271667.64,
    "totalRevenueAED": 3476366.92,
    "operRevenueAED": 2478667.33,
    "standbyRevenueAED": 997699.31,
    "totalRevenue": 946594.12,
    "operRevenue": 674926.48,
    "standbyRevenue": 271667.64,
    "operDays": 3765.0,
    "standbyDays": 15686.0,
    "toolsCount": 1423,
    "jobsCount": 57
  },
  {
    "contractKey": "HALLIBURTON - UAE - HALLIBURTON - UAE",
    "contract": "HALLIBURTON - UAE",
    "client": "HALLIBURTON - UAE",
    "currency": "USD",
    "nativeRevenue": 411690.0,
    "nativeOperRevenue": 328365.0,
    "nativeStandbyRevenue": 83325.0,
    "totalRevenueUSD": 411690.0,
    "operRevenueUSD": 328365.0,
    "standbyRevenueUSD": 83325.0,
    "totalRevenueAED": 1511931.49,
    "operRevenueAED": 1205920.43,
    "standbyRevenueAED": 306011.06,
    "totalRevenue": 411690.0,
    "operRevenue": 328365.0,
    "standbyRevenue": 83325.0,
    "operDays": 193.0,
    "standbyDays": 3883.0,
    "toolsCount": 117,
    "jobsCount": 7
  },
  {
    "contractKey": "ITS - UAE - ITS (NABORS)",
    "contract": "ITS - UAE",
    "client": "ITS (NABORS)",
    "currency": "USD",
    "nativeRevenue": 375554.38,
    "nativeOperRevenue": 251926.74,
    "nativeStandbyRevenue": 123627.64,
    "totalRevenueUSD": 375554.38,
    "operRevenueUSD": 251926.74,
    "standbyRevenueUSD": 123627.64,
    "totalRevenueAED": 1379223.48,
    "operRevenueAED": 925200.92,
    "standbyRevenueAED": 454022.55,
    "totalRevenue": 375554.38,
    "operRevenue": 251926.74,
    "standbyRevenue": 123627.64,
    "operDays": 465.0,
    "standbyDays": 11228.0,
    "toolsCount": 299,
    "jobsCount": 94
  }
];
