// Autogenerated lightweight commercial summary for Operations Dashboard and Analytics
export interface RevenueSummaryData {
  fxRateUSDToAED: number;
  totalRevenueUSD: number;
  totalOperRevenueUSD: number;
  totalStandbyRevenueUSD: number;
  totalRevenueAED: number;
  totalOperRevenueAED: number;
  totalStandbyRevenueAED: number;
  totalRevenue: number;
  totalOperRevenue: number;
  totalStandbyRevenue: number;
  totalOperDays: number;
  totalStandbyDays: number;
  totalTools: number;
  totalCategories: number;
  totalSizes: number;
  totalContracts: number;
}

export interface CategoryRevenueSummary {
  category: string;
  totalRevenueUSD: number;
  operRevenueUSD: number;
  standbyRevenueUSD: number;
  totalRevenueAED: number;
  operRevenueAED: number;
  standbyRevenueAED: number;
  totalRevenue: number;
  operRevenue: number;
  standbyRevenue: number;
  operDays: number;
  standbyDays: number;
  toolCount?: number;
  toolsCount?: number;
  jobsCount: number;
}

export interface ContractRevenueSummary {
  contractKey?: string;
  contract: string;
  client: string;
  currency: 'AED' | 'USD';
  nativeRevenue: number;
  nativeOperRevenue: number;
  nativeStandbyRevenue: number;
  totalRevenueUSD: number;
  operRevenueUSD: number;
  standbyRevenueUSD: number;
  totalRevenueAED: number;
  operRevenueAED: number;
  standbyRevenueAED: number;
  totalRevenue: number;
  operRevenue: number;
  standbyRevenue: number;
  operDays?: number;
  standbyDays?: number;
  toolCount?: number;
  toolsCount?: number;
  jobsCount: number;
}

export const REVENUE_SUMMARY: RevenueSummaryData = {
  "fxRateUSDToAED": 3.6725,
  "totalRevenueUSD": 9132396.26,
  "totalOperRevenueUSD": 2295351.07,
  "totalStandbyRevenueUSD": 5616845.38,
  "totalRevenueAED": 33538735.0,
  "totalOperRevenueAED": 8429673.37,
  "totalStandbyRevenueAED": 20627881.54,
  "totalRevenue": 9132396.26,
  "totalOperRevenue": 2295351.07,
  "totalStandbyRevenue": 5616845.38,
  "totalOperDays": 63971.0,
  "totalStandbyDays": 675170.0,
  "totalTools": 6882,
  "totalCategories": 116,
  "totalSizes": 139,
  "totalContracts": 28
};

export const TOP_CATEGORIES_REVENUE: CategoryRevenueSummary[] = [
  {
    "category": "DRILLING JAR",
    "totalRevenueUSD": 2895695.06,
    "operRevenueUSD": 866635.73,
    "standbyRevenueUSD": 2013265.54,
    "totalRevenueAED": 10634447.96,
    "operRevenueAED": 3182719.77,
    "standbyRevenueAED": 7393726.77,
    "totalRevenue": 2895695.06,
    "operRevenue": 866635.73,
    "standbyRevenue": 2013265.54,
    "operDays": 4202.0,
    "standbyDays": 13061.0,
    "toolsCount": 225,
    "jobsCount": 300
  },
  {
    "category": "OTHER DOWNHOLE TOOL",
    "totalRevenueUSD": 1663326.4,
    "operRevenueUSD": 487010.49,
    "standbyRevenueUSD": 911271.43,
    "totalRevenueAED": 6108566.99,
    "operRevenueAED": 1788544.42,
    "standbyRevenueAED": 3346646.22,
    "totalRevenue": 1663326.4,
    "operRevenue": 487010.49,
    "standbyRevenue": 911271.43,
    "operDays": 4831.0,
    "standbyDays": 63237.0,
    "toolsCount": 1139,
    "jobsCount": 951
  },
  {
    "category": "STRING STAB",
    "totalRevenueUSD": 772701.77,
    "operRevenueUSD": 241529.62,
    "standbyRevenueUSD": 490781.29,
    "totalRevenueAED": 2837749.72,
    "operRevenueAED": 887016.29,
    "standbyRevenueAED": 1802399.07,
    "totalRevenue": 772701.77,
    "operRevenue": 241529.62,
    "standbyRevenue": 490781.29,
    "operDays": 5064.0,
    "standbyDays": 15225.0,
    "toolsCount": 327,
    "jobsCount": 284
  },
  {
    "category": "DRILL COLLAR",
    "totalRevenueUSD": 481698.18,
    "operRevenueUSD": 147821.98,
    "standbyRevenueUSD": 329696.16,
    "totalRevenueAED": 1769036.11,
    "operRevenueAED": 542875.02,
    "standbyRevenueAED": 1210809.83,
    "totalRevenue": 481698.18,
    "operRevenue": 147821.98,
    "standbyRevenue": 329696.16,
    "operDays": 2196.0,
    "standbyDays": 5747.0,
    "toolsCount": 113,
    "jobsCount": 43
  },
  {
    "category": "FLOAT SUB",
    "totalRevenueUSD": 401535.21,
    "operRevenueUSD": 183655.16,
    "standbyRevenueUSD": 217879.36,
    "totalRevenueAED": 1474638.87,
    "operRevenueAED": 674474.47,
    "standbyRevenueAED": 800164.39,
    "totalRevenue": 401535.21,
    "operRevenue": 183655.16,
    "standbyRevenue": 217879.36,
    "operDays": 10817.0,
    "standbyDays": 20533.0,
    "toolsCount": 203,
    "jobsCount": 26
  },
  {
    "category": "DIVERTER",
    "totalRevenueUSD": 373379.03,
    "operRevenueUSD": 0.0,
    "standbyRevenueUSD": 0.0,
    "totalRevenueAED": 1371234.47,
    "operRevenueAED": 0.0,
    "standbyRevenueAED": 0.0,
    "totalRevenue": 373379.03,
    "operRevenue": 0.0,
    "standbyRevenue": 0.0,
    "operDays": 293.0,
    "standbyDays": 299.0,
    "toolsCount": 25,
    "jobsCount": 91
  },
  {
    "category": "OVERSHOT",
    "totalRevenueUSD": 327187.54,
    "operRevenueUSD": 48521.32,
    "standbyRevenueUSD": 278666.22,
    "totalRevenueAED": 1201595.75,
    "operRevenueAED": 178194.48,
    "standbyRevenueAED": 1023400.92,
    "totalRevenue": 327187.54,
    "operRevenue": 48521.32,
    "standbyRevenue": 278666.22,
    "operDays": 841.0,
    "standbyDays": 73173.0,
    "toolsCount": 511,
    "jobsCount": 395
  },
  {
    "category": "SUB",
    "totalRevenueUSD": 308358.3,
    "operRevenueUSD": 30938.64,
    "standbyRevenueUSD": 134139.76,
    "totalRevenueAED": 1132445.7,
    "operRevenueAED": 113622.15,
    "standbyRevenueAED": 492628.07,
    "totalRevenue": 308358.3,
    "operRevenue": 30938.64,
    "standbyRevenue": 134139.76,
    "operDays": 2837.0,
    "standbyDays": 11714.0,
    "toolsCount": 150,
    "jobsCount": 352
  },
  {
    "category": "TORQUE REDUCER CLAMPS",
    "totalRevenueUSD": 198942.92,
    "operRevenueUSD": 0.0,
    "standbyRevenueUSD": 0.0,
    "totalRevenueAED": 730617.88,
    "operRevenueAED": 0.0,
    "standbyRevenueAED": 0.0,
    "totalRevenue": 198942.92,
    "operRevenue": 0.0,
    "standbyRevenue": 0.0,
    "operDays": 8273.0,
    "standbyDays": 1834.0,
    "toolsCount": 2,
    "jobsCount": 5
  },
  {
    "category": "JUNK MILL",
    "totalRevenueUSD": 194360.79,
    "operRevenueUSD": 5553.43,
    "standbyRevenueUSD": 188807.36,
    "totalRevenueAED": 713789.79,
    "operRevenueAED": 20394.97,
    "standbyRevenueAED": 693394.82,
    "totalRevenue": 194360.79,
    "operRevenue": 5553.43,
    "standbyRevenue": 188807.36,
    "operDays": 292.0,
    "standbyDays": 17656.0,
    "toolsCount": 154,
    "jobsCount": 395
  }
];

export const TOP_CONTRACTS_REVENUE: ContractRevenueSummary[] = [
  {
    "contractKey": "4700024096 - ADNOC DRILLING - RENTALS",
    "contract": "4700024096",
    "client": "ADNOC DRILLING - RENTALS",
    "currency": "AED",
    "nativeRevenue": 19708565.83,
    "nativeOperRevenue": 6849528.43,
    "nativeStandbyRevenue": 12859037.39,
    "totalRevenueUSD": 5366522.83,
    "operRevenueUSD": 1865086.96,
    "standbyRevenueUSD": 3501434.6,
    "totalRevenueAED": 19708565.83,
    "operRevenueAED": 6849528.43,
    "standbyRevenueAED": 12859037.39,
    "totalRevenue": 5366522.83,
    "operRevenue": 1865086.96,
    "standbyRevenue": 3501434.6,
    "operDays": 25597.0,
    "standbyDays": 60211.0,
    "toolsCount": 760,
    "jobsCount": 24
  },
  {
    "contractKey": "4700023861 - ADNOC ONSHORE - RENTALS",
    "contract": "4700023861",
    "client": "ADNOC ONSHORE - RENTALS",
    "currency": "USD",
    "nativeRevenue": 1443795.46,
    "nativeOperRevenue": 110093.47,
    "nativeStandbyRevenue": 113503.45,
    "totalRevenueUSD": 1443795.46,
    "operRevenueUSD": 110093.47,
    "standbyRevenueUSD": 113503.45,
    "totalRevenueAED": 5302338.84,
    "operRevenueAED": 404318.35,
    "standbyRevenueAED": 416841.02,
    "totalRevenue": 1443795.46,
    "operRevenue": 110093.47,
    "standbyRevenue": 113503.45,
    "operDays": 25763.0,
    "standbyDays": 13480.0,
    "toolsCount": 1063,
    "jobsCount": 451
  },
  {
    "contractKey": "444558 - ADNOC OFFSHORE",
    "contract": "444558",
    "client": "ADNOC OFFSHORE",
    "currency": "USD",
    "nativeRevenue": 879821.3,
    "nativeOperRevenue": 30471.56,
    "nativeStandbyRevenue": 849349.74,
    "totalRevenueUSD": 879821.3,
    "operRevenueUSD": 30471.56,
    "standbyRevenueUSD": 849349.74,
    "totalRevenueAED": 3231143.21,
    "operRevenueAED": 111906.86,
    "standbyRevenueAED": 3119236.3,
    "totalRevenue": 879821.3,
    "operRevenue": 30471.56,
    "standbyRevenue": 849349.74,
    "operDays": 2923.0,
    "standbyDays": 256701.0,
    "toolsCount": 3850,
    "jobsCount": 381
  },
  {
    "contractKey": "444558.REV.1 - ADNOC OFFSHORE",
    "contract": "444558.REV.1",
    "client": "ADNOC OFFSHORE",
    "currency": "USD",
    "nativeRevenue": 345003.68,
    "nativeOperRevenue": 11098.42,
    "nativeStandbyRevenue": 333905.26,
    "totalRevenueUSD": 345003.68,
    "operRevenueUSD": 11098.42,
    "standbyRevenueUSD": 333905.26,
    "totalRevenueAED": 1267025.73,
    "operRevenueAED": 40758.92,
    "standbyRevenueAED": 1226266.78,
    "totalRevenue": 345003.68,
    "operRevenue": 11098.42,
    "standbyRevenue": 333905.26,
    "operDays": 646.0,
    "standbyDays": 93214.0,
    "toolsCount": 1826,
    "jobsCount": 130
  },
  {
    "contractKey": "16358.13.Rev1 - ADNOC ONSHORE - FISHING",
    "contract": "16358.13.Rev1",
    "client": "ADNOC ONSHORE - FISHING",
    "currency": "USD",
    "nativeRevenue": 289580.75,
    "nativeOperRevenue": 108629.12,
    "nativeStandbyRevenue": 180951.63,
    "totalRevenueUSD": 289580.75,
    "operRevenueUSD": 108629.12,
    "standbyRevenueUSD": 180951.63,
    "totalRevenueAED": 1063485.3,
    "operRevenueAED": 398940.27,
    "standbyRevenueAED": 664544.86,
    "totalRevenue": 289580.75,
    "operRevenue": 108629.12,
    "standbyRevenue": 180951.63,
    "operDays": 2852.0,
    "standbyDays": 15232.0,
    "toolsCount": 1423,
    "jobsCount": 57
  },
  {
    "contractKey": "16358.13.Rev2 - ADNOC ONSHORE - FISHING",
    "contract": "16358.13.Rev2",
    "client": "ADNOC ONSHORE - FISHING",
    "currency": "USD",
    "nativeRevenue": 265166.29,
    "nativeOperRevenue": 99349.7,
    "nativeStandbyRevenue": 165816.59,
    "totalRevenueUSD": 265166.29,
    "operRevenueUSD": 99349.7,
    "standbyRevenueUSD": 165816.59,
    "totalRevenueAED": 973823.16,
    "operRevenueAED": 364861.72,
    "standbyRevenueAED": 608961.03,
    "totalRevenue": 265166.29,
    "operRevenue": 99349.7,
    "standbyRevenue": 165816.59,
    "operDays": 2874.0,
    "standbyDays": 13839.0,
    "toolsCount": 1493,
    "jobsCount": 56
  },
  {
    "contractKey": "444558 - ADNOC",
    "contract": "444558",
    "client": "ADNOC",
    "currency": "USD",
    "nativeRevenue": 244129.3,
    "nativeOperRevenue": 20096.0,
    "nativeStandbyRevenue": 224033.3,
    "totalRevenueUSD": 244129.3,
    "operRevenueUSD": 20096.0,
    "standbyRevenueUSD": 224033.3,
    "totalRevenueAED": 896564.62,
    "operRevenueAED": 73802.62,
    "standbyRevenueAED": 822761.99,
    "totalRevenue": 244129.3,
    "operRevenue": 20096.0,
    "standbyRevenue": 224033.3,
    "operDays": 956.0,
    "standbyDays": 102857.0,
    "toolsCount": 2027,
    "jobsCount": 59
  },
  {
    "contractKey": "4700024608 - UDR - ADNOC DRILLING - FISHING",
    "contract": "4700024608 - UDR",
    "client": "ADNOC DRILLING - FISHING",
    "currency": "USD",
    "nativeRevenue": 153764.37,
    "nativeOperRevenue": 909.56,
    "nativeStandbyRevenue": 152854.81,
    "totalRevenueUSD": 153764.37,
    "operRevenueUSD": 909.56,
    "standbyRevenueUSD": 152854.81,
    "totalRevenueAED": 564699.62,
    "operRevenueAED": 3340.37,
    "standbyRevenueAED": 561359.26,
    "totalRevenue": 153764.37,
    "operRevenue": 909.56,
    "standbyRevenue": 152854.81,
    "operDays": 115.0,
    "standbyDays": 69783.0,
    "toolsCount": 811,
    "jobsCount": 129
  },
  {
    "contractKey": "4700015149 - ADNOC DRILLING - FISHING",
    "contract": "4700015149",
    "client": "ADNOC DRILLING - FISHING",
    "currency": "USD",
    "nativeRevenue": 41146.31,
    "nativeOperRevenue": 1145.04,
    "nativeStandbyRevenue": 40001.27,
    "totalRevenueUSD": 41146.31,
    "operRevenueUSD": 1145.04,
    "standbyRevenueUSD": 40001.27,
    "totalRevenueAED": 151109.86,
    "operRevenueAED": 4205.16,
    "standbyRevenueAED": 146904.7,
    "totalRevenue": 41146.31,
    "operRevenue": 1145.04,
    "standbyRevenue": 40001.27,
    "operDays": 91.0,
    "standbyDays": 12996.0,
    "toolsCount": 299,
    "jobsCount": 17
  },
  {
    "contractKey": "ITS - UAE - ITS (NABORS)",
    "contract": "ITS - UAE",
    "client": "ITS (NABORS)",
    "currency": "USD",
    "nativeRevenue": 36012.66,
    "nativeOperRevenue": 3695.71,
    "nativeStandbyRevenue": 32316.95,
    "totalRevenueUSD": 36012.66,
    "operRevenueUSD": 3695.71,
    "standbyRevenueUSD": 32316.95,
    "totalRevenueAED": 132256.5,
    "operRevenueAED": 13572.47,
    "standbyRevenueAED": 118684.03,
    "totalRevenue": 36012.66,
    "operRevenue": 3695.71,
    "standbyRevenue": 32316.95,
    "operDays": 146.0,
    "standbyDays": 10619.0,
    "toolsCount": 299,
    "jobsCount": 94
  },
  {
    "contractKey": "TW-2025-1026 - TURNWELL",
    "contract": "TW-2025-1026",
    "client": "TURNWELL",
    "currency": "USD",
    "nativeRevenue": 25360.52,
    "nativeOperRevenue": 20797.8,
    "nativeStandbyRevenue": 4562.72,
    "totalRevenueUSD": 25360.52,
    "operRevenueUSD": 20797.8,
    "standbyRevenueUSD": 4562.72,
    "totalRevenueAED": 93136.54,
    "operRevenueAED": 76379.96,
    "standbyRevenueAED": 16756.6,
    "totalRevenue": 25360.52,
    "operRevenue": 20797.8,
    "standbyRevenue": 4562.72,
    "operDays": 227.0,
    "standbyDays": 3143.0,
    "toolsCount": 110,
    "jobsCount": 26
  },
  {
    "contractKey": "4700012465 - ADNOC ONSHORE - RENTALS",
    "contract": "4700012465",
    "client": "ADNOC ONSHORE - RENTALS",
    "currency": "USD",
    "nativeRevenue": 11200.0,
    "nativeOperRevenue": 11200.0,
    "nativeStandbyRevenue": 0.0,
    "totalRevenueUSD": 11200.0,
    "operRevenueUSD": 11200.0,
    "standbyRevenueUSD": 0.0,
    "totalRevenueAED": 41132.0,
    "operRevenueAED": 41132.0,
    "standbyRevenueAED": 0.0,
    "totalRevenue": 11200.0,
    "operRevenue": 11200.0,
    "standbyRevenue": 0.0,
    "operDays": 968.0,
    "standbyDays": 4604.0,
    "toolsCount": 257,
    "jobsCount": 60
  }
];
