// Autogenerated lightweight commercial summary for Operations Dashboard and Analytics
export interface RevenueSummaryData {
  totalRevenue: number;
  totalOperRevenue: number;
  totalStandbyRevenue: number;
  totalOperDays: number;
  totalStandbyDays: number;
  totalTools: number;
  totalCategories: number;
  totalSizes: number;
  totalContracts: number;
}

export interface CategoryRevenueSummary {
  category: string;
  totalRevenue: number;
  operRevenue: number;
  standbyRevenue: number;
  operDays: number;
  standbyDays: number;
  toolCount?: number;
  toolsCount?: number;
  jobsCount: number;
}

export interface ContractRevenueSummary {
  contractKey?: string;
  contract: string;
  client: string;
  totalRevenue: number;
  operRevenue: number;
  standbyRevenue: number;
  operDays?: number;
  standbyDays?: number;
  toolCount?: number;
  toolsCount?: number;
  jobsCount: number;
}

export const REVENUE_SUMMARY: RevenueSummaryData = {
  "totalRevenue": 23474439.26,
  "totalOperRevenue": 7279792.54,
  "totalStandbyRevenue": 14974448.17,
  "totalOperDays": 63971.0,
  "totalStandbyDays": 675170.0,
  "totalTools": 6882,
  "totalCategories": 116,
  "totalSizes": 139,
  "totalContracts": 28
};

export const TOP_CATEGORIES_REVENUE: CategoryRevenueSummary[] = [
  {
    "category": "DRILLING JAR",
    "totalRevenue": 10500923.12,
    "operRevenue": 3158268.03,
    "standbyRevenue": 7326861.66,
    "operDays": 4202.0,
    "standbyDays": 13061.0,
    "toolsCount": 225,
    "jobsCount": 300
  },
  {
    "category": "OTHER DOWNHOLE TOOL",
    "totalRevenue": 3891024.48,
    "operRevenue": 1572846.1,
    "standbyRevenue": 2053133.73,
    "operDays": 4831.0,
    "standbyDays": 63237.0,
    "toolsCount": 1139,
    "jobsCount": 951
  },
  {
    "category": "STRING STAB",
    "totalRevenue": 2493900.21,
    "operRevenue": 786892.68,
    "standbyRevenue": 1666616.95,
    "operDays": 5064.0,
    "standbyDays": 15225.0,
    "toolsCount": 327,
    "jobsCount": 284
  },
  {
    "category": "DRILL COLLAR",
    "totalRevenue": 1749920.13,
    "operRevenue": 537201.3,
    "standbyRevenue": 1208538.78,
    "operDays": 2196.0,
    "standbyDays": 5747.0,
    "toolsCount": 113,
    "jobsCount": 43
  },
  {
    "category": "FLOAT SUB",
    "totalRevenue": 1465938.28,
    "operRevenue": 673480.3,
    "standbyRevenue": 792457.97,
    "operDays": 10817.0,
    "standbyDays": 20533.0,
    "toolsCount": 203,
    "jobsCount": 26
  },
  {
    "category": "STABILIZER",
    "totalRevenue": 483769.26,
    "operRevenue": 180615.43,
    "standbyRevenue": 303153.83,
    "operDays": 757.0,
    "standbyDays": 1391.0,
    "toolsCount": 31,
    "jobsCount": 30
  },
  {
    "category": "DIVERTER",
    "totalRevenue": 373379.03,
    "operRevenue": 0.0,
    "standbyRevenue": 0.0,
    "operDays": 293.0,
    "standbyDays": 299.0,
    "toolsCount": 25,
    "jobsCount": 91
  },
  {
    "category": "OVERSHOT",
    "totalRevenue": 327187.54,
    "operRevenue": 48521.32,
    "standbyRevenue": 278666.22,
    "operDays": 841.0,
    "standbyDays": 73173.0,
    "toolsCount": 511,
    "jobsCount": 395
  },
  {
    "category": "SUB",
    "totalRevenue": 308358.3,
    "operRevenue": 30938.64,
    "standbyRevenue": 134139.76,
    "operDays": 2837.0,
    "standbyDays": 11714.0,
    "toolsCount": 150,
    "jobsCount": 352
  },
  {
    "category": "TORQUE REDUCER CLAMPS",
    "totalRevenue": 198942.92,
    "operRevenue": 0.0,
    "standbyRevenue": 0.0,
    "operDays": 8273.0,
    "standbyDays": 1834.0,
    "toolsCount": 2,
    "jobsCount": 5
  },
  {
    "category": "JUNK MILL",
    "totalRevenue": 194360.79,
    "operRevenue": 5553.43,
    "standbyRevenue": 188807.36,
    "operDays": 292.0,
    "standbyDays": 17656.0,
    "toolsCount": 154,
    "jobsCount": 395
  },
  {
    "category": "FISHING JAR",
    "totalRevenue": 172210.8,
    "operRevenue": 23644.93,
    "standbyRevenue": 148565.87,
    "operDays": 191.0,
    "standbyDays": 5595.0,
    "toolsCount": 49,
    "jobsCount": 276
  },
  {
    "category": "RELEASING SPEAR",
    "totalRevenue": 139271.39,
    "operRevenue": 2911.98,
    "standbyRevenue": 136359.41,
    "operDays": 100.0,
    "standbyDays": 14716.0,
    "toolsCount": 114,
    "jobsCount": 264
  },
  {
    "category": "FLOAT VALVE",
    "totalRevenue": 135934.7,
    "operRevenue": 68531.42,
    "standbyRevenue": 67403.28,
    "operDays": 1131.0,
    "standbyDays": 1770.0,
    "toolsCount": 86,
    "jobsCount": 14
  },
  {
    "category": "DRILL PIPE",
    "totalRevenue": 113840.52,
    "operRevenue": 2104.01,
    "standbyRevenue": 1612.43,
    "operDays": 12762.0,
    "standbyDays": 6342.0,
    "toolsCount": 31,
    "jobsCount": 43
  }
];

export const TOP_CONTRACTS_REVENUE: ContractRevenueSummary[] = [
  {
    "contractKey": "4700024096 - ADNOC DRILLING - RENTALS",
    "contract": "4700024096",
    "client": "ADNOC DRILLING - RENTALS",
    "totalRevenue": 19708565.83,
    "operRevenue": 6849528.43,
    "standbyRevenue": 12859037.39,
    "operDays": 25597.0,
    "standbyDays": 60211.0,
    "toolsCount": 760,
    "jobsCount": 24
  },
  {
    "contractKey": "4700023861 - ADNOC ONSHORE - RENTALS",
    "contract": "4700023861",
    "client": "ADNOC ONSHORE - RENTALS",
    "totalRevenue": 1443795.46,
    "operRevenue": 110093.47,
    "standbyRevenue": 113503.45,
    "operDays": 25763.0,
    "standbyDays": 13480.0,
    "toolsCount": 1063,
    "jobsCount": 451
  },
  {
    "contractKey": "444558 - ADNOC OFFSHORE",
    "contract": "444558",
    "client": "ADNOC OFFSHORE",
    "totalRevenue": 879821.3,
    "operRevenue": 30471.56,
    "standbyRevenue": 849349.74,
    "operDays": 2923.0,
    "standbyDays": 256701.0,
    "toolsCount": 3850,
    "jobsCount": 381
  },
  {
    "contractKey": "444558.REV.1 - ADNOC OFFSHORE",
    "contract": "444558.REV.1",
    "client": "ADNOC OFFSHORE",
    "totalRevenue": 345003.68,
    "operRevenue": 11098.42,
    "standbyRevenue": 333905.26,
    "operDays": 646.0,
    "standbyDays": 93214.0,
    "toolsCount": 1826,
    "jobsCount": 130
  },
  {
    "contractKey": "16358.13.Rev1 - ADNOC ONSHORE - FISHING",
    "contract": "16358.13.Rev1",
    "client": "ADNOC ONSHORE - FISHING",
    "totalRevenue": 289580.75,
    "operRevenue": 108629.12,
    "standbyRevenue": 180951.63,
    "operDays": 2852.0,
    "standbyDays": 15232.0,
    "toolsCount": 1423,
    "jobsCount": 57
  },
  {
    "contractKey": "16358.13.Rev2 - ADNOC ONSHORE - FISHING",
    "contract": "16358.13.Rev2",
    "client": "ADNOC ONSHORE - FISHING",
    "totalRevenue": 265166.29,
    "operRevenue": 99349.7,
    "standbyRevenue": 165816.59,
    "operDays": 2874.0,
    "standbyDays": 13839.0,
    "toolsCount": 1493,
    "jobsCount": 56
  },
  {
    "contractKey": "444558 - ADNOC",
    "contract": "444558",
    "client": "ADNOC",
    "totalRevenue": 244129.3,
    "operRevenue": 20096.0,
    "standbyRevenue": 224033.3,
    "operDays": 956.0,
    "standbyDays": 102857.0,
    "toolsCount": 2027,
    "jobsCount": 59
  },
  {
    "contractKey": "4700024608 - UDR - ADNOC DRILLING - FISHING",
    "contract": "4700024608 - UDR",
    "client": "ADNOC DRILLING - FISHING",
    "totalRevenue": 153764.37,
    "operRevenue": 909.56,
    "standbyRevenue": 152854.81,
    "operDays": 115.0,
    "standbyDays": 69783.0,
    "toolsCount": 811,
    "jobsCount": 129
  },
  {
    "contractKey": "4700015149 - ADNOC DRILLING - FISHING",
    "contract": "4700015149",
    "client": "ADNOC DRILLING - FISHING",
    "totalRevenue": 41146.31,
    "operRevenue": 1145.04,
    "standbyRevenue": 40001.27,
    "operDays": 91.0,
    "standbyDays": 12996.0,
    "toolsCount": 299,
    "jobsCount": 17
  },
  {
    "contractKey": "ITS - UAE - ITS (NABORS)",
    "contract": "ITS - UAE",
    "client": "ITS (NABORS)",
    "totalRevenue": 36012.66,
    "operRevenue": 3695.71,
    "standbyRevenue": 32316.95,
    "operDays": 146.0,
    "standbyDays": 10619.0,
    "toolsCount": 299,
    "jobsCount": 94
  }
];
